### ISSUE TITLE
Is there a plan to provide an ollama version?

### ISSUE THREAD

**Issue by utopeadia** [WePOINTS/WePOINTS#12]
As the title suggests, ollama is a good choice for simple and quick use

**Comment by WePOINTS** [comment]
Thank you for your interest in WePOINTS. We plan to support Ollama and Hugging Face demos in the future. Stay tuned!

**Comment by utopeadia** [comment]
> Thank you for your interest in WePOINTS. We plan to support Ollama and Hugging Face demos in the future. Stay tuned!

nice job

**Comment by WePOINTS** [comment]
> > Thank you for your interest in WePOINTS. We plan to support Ollama and Hugging Face demos in the future. Stay tuned!
> 
> nice job

If you have any further questions, please feel free to reopen this issue.
