### ISSUE TITLE
Hi, opensourcing the pretrain data filtering method (code) ?

### ISSUE THREAD

**Issue by luohao123** [WePOINTS/WePOINTS#13]
Hi, opensourcing the pretrain data filtering method (code) ?

**Comment by WePOINTS** [comment]
Thank you for your interests in this project. @ZZhongYin will give a demo code about the pre-training data filtering strategy using perplexity.

**Comment by luohao123** [comment]
Thanks, is there any time schedule on this

**Comment by ZZhongYin** [comment]
Thanks for your interest in this project. The demo code about the pre-training data filtering strategy using perplexity is anticipated to be released before November 1st.

**Comment by YuanLiuuuuuu** [comment]
> Hi, opensourcing the pretrain data filtering method (code) ?

Sorry for the late reply. We have added a demo script to filter the pre-training data by perplexity, and please refer to the PR [here](https://github.com/WePOINTS/WePOINTS/pull/14).

**Comment by YuanLiuuuuuu** [comment]
Close as being solved. If you have any questions, feel free to reopen it.
