### ISSUE TITLE
Share some more details on pretrained data filtering

### ISSUE THREAD

**Issue by MonolithFoundation** [WePOINTS/WePOINTS#17]
Hi, which pretrained data filtered and how many percentage labeling were wrong?

**Comment by YuanLiuuuuuu** [comment]
Thank you for your interest in POINTS. The final 1 million pre-trained data points were obtained by filtering 5 million data points, which were randomly sampled from LAION-5B(en). This filtering process, which utilized perplexity (ppl) as a criterion, resulted in approximately 80% of the data being excluded.
