### ISSUE TITLE
Environment Setup Problem and Fix

### ISSUE THREAD

**Issue by KejiaZhang-Robust** [WePOINTS/WePOINTS#19]
Hi, I encountered an issue while following the tutorial to set up the environment. Here’s what happened:
1. I created a new environment using:
conda create -n wepoint python=3.10 -y
2. Then I ran:
pip install -e .

However, I got the following error:
```
ImportError: requires the protobuf library but it was not found in your environment. 
Checkout the instructions on the installation page of its repo: 
https://github.com/protocolbuffers/protobuf/tree/master/python#installation 
and follow the ones that match your environment. Please note that you may need to 
restart your runtime after installation.
```

Solution:

To fix this, I had to manually install protobuf:
```
pip install protobuf
```
After that, the code started working, but I also noticed that it requires the accelerate package version >=0.26.0. So I installed it as well:
```
pip install accelerate>=0.26.0
```

**Comment by YuanLiuuuuuu** [comment]
Could you please provide the complete code snippet you are using?
