### ISSUE TITLE
Any plan of releasing finetuning code and script?

### ISSUE THREAD

**Issue by Elenore1997** [WePOINTS/WePOINTS#30]
Hi, great work of MLLM! I am wondering that do you have any plan of releasing finetuning code and script? Thanks in advance.

**Comment by YuanLiuuuuuu** [comment]
Thank you for your interest in our project. Since POINTS1.5 is trained using an internal framework developed by WeChat, it is not feasible to open source it at this time.

**Comment by Elenore1997** [comment]
> Thank you for your interest in our project. Since POINTS1.5 is trained using an internal framework developed by WeChat, it is not feasible to open source it at this time.

Thanks for your reply! Or is it convenient for you to provide the training data format, system prompt that used for fine-tuning, so that we can try to further tuing for some other tasks?

**Comment by WePOINTS** [comment]
Following POINTS1.0, we do no add any system prompt during visual instruction tuning.

**Comment by YuanLiuuuuuu** [comment]
> > Thank you for your interest in our project. Since POINTS1.5 is trained using an internal framework developed by WeChat, it is not feasible to open source it at this time.
> 
> Thanks for your reply! Or is it convenient for you to provide the training data format, system prompt that used for fine-tuning, so that we can try to further tuing for some other tasks?

And POINTS1.5 technical report gives the chat template used in pre-training and visual instruction tuning.

**Comment by YuanLiuuuuuu** [comment]
If you hava any further questions, feel free reopen this issue
