### ISSUE TITLE
Inquiry about ViT Initialization for POINTS1.5

### ISSUE THREAD

**Issue by JaronTHU** [WePOINTS/WePOINTS#34]
First of all, I want to commend you on the fantastic work you've done with POINTS1.5. The implementation is clean, and the results are impressive. It's clear that a lot of thought and effort has gone into making this as effective and user-friendly as possible.

I have a question regarding the initialization of the ViT in POINTS1.5. As you mention in paper, you employ **the Qwen2-VL vision encoder** before training POINTS1.5. I am curious about which Qwen2-VL ViT do you choose to use specifically? As far as I know, there are 6 open-source Qwen2-VL models:
* Qwen2-VL-2B
* Qwen2-VL-2B-Instruct
* Qwen2-VL-7B
* Qwen2-VL-7B-Instruct
* Qwen2-VL-72B
* Qwen2-VL-72B-Instruct

Thank you for your time and assistance! Looking forward to your reply!

**Comment by YuanLiuuuuuu** [comment]
Thank you for your interests in POINTS1.5. As for the initialization of NaViT in POINTS1.5, we choose that from Qwen2-VL-7B-Instruct.

**Comment by JaronTHU** [comment]
Thank you for your reply!
