### ISSUE TITLE
do you use  individual select in POINTS1.5

### ISSUE THREAD

**Issue by lijiaoyang** [WePOINTS/WePOINTS#35]

**Comment by YuanLiuuuuuu** [comment]
As mentioned in the technical report, all visual instruction tuning datasets are derived from POINTS1.0. Therefore, we do not use ``individual select`` to include additional datasets to enhance performance. For the newly introduced Chinese OCR datasets, we include all of them in the original visual instruction tuning set without selection.

However, you can still use ``individual select`` to add datasets at any stage of your visual instruction tuning process, which is expected to further improve performance.
