### ISSUE TITLE
Without image can answer

### ISSUE THREAD

**Issue by LKELN** [WePOINTS/WePOINTS#36]
We then train the model with the filtered dataset but observe slightly degraded performance. This phenomenon is consistent with previous works , which suggest that pure-text data is helpful in maintaining the capability of the pre-trained LLM.
You mentioned in the technical report that removing question-answer pairs that can be answered without images would lead to a decline in performance. So, did you not use this strategy for training?

**Comment by YuanLiuuuuuu** [comment]
Yes, we do not adopt this strategy for filtering the SFT dataset. As filtering out questions that can be answered without images is intuitive, we mention it in the technical report solely to share our experience with the community.

**Comment by LKELN** [comment]
Thank you very much for your contribution.
